Simplify setup
intel/openfl pull request #1187
Opened 2024-12-03 08:44 UTC by MasterSkepticista

About this PR:
* https://github.com/securefederatedai/openfl/pull/1187/commits/6191d8222c8efecf2ed83b092a0b44c9ffa42881 Removes traces of `log_metric`, `log_metric_callback` and `write_metric` as they are not used throughout, and not defined as per python best practices.
* https://github.com/securefederatedai/openfl/pull/1187/commits/e17172ec53f441890d9a52380060e636fc0cc894 Populates all subpackages automatically using setuptools `find_packages`.
* https://github.com/securefederatedai/openfl/pull/1187/commits/6017900b44d3992fd4c9b30058a140dbca88d1a2 Shrinks requirement footprint significantly by removing unused packages, or those not required as a bare minimum by `openfl`.
* Interactive API CI tests have been disabled [here](https://github.com/securefederatedai/openfl/actions)

2024-12-03 16:19 UTC, psfoley commented on setup.py
> +    long_description=open("README.md", encoding="utf-8").read(),
👍

2024-12-03 23:55 UTC, psfoley requested changes
The change of removing `log_metric`, `log_metric_callback` and `write_metric` should be reverted. This would remove our ability to publish metrics to Tensorboard: https://github.com/securefederatedai/openfl/blob/7c53fb75a4ab22465c003eb06ad9862b0b76d5c8/docs/developer_guide/advanced_topics/log_metric_callback.rst#L4

Writing logs in the tensorboard format for later analysis is the default in many ([1](https://github.com/securefederatedai/openfl/blob/develop/openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml#L12),[2](https://github.com/securefederatedai/openfl/blob/develop/openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml#L12),[3](https://github.com/securefederatedai/openfl/blob/7c53fb75a4ab22465c003eb06ad9862b0b76d5c8/openfl-workspace/torch_llm_horovod/plan/plan.yaml#L13)) of the existing TaskRunner API examples. This capability should not be removed unless there is a plan to replace it.

2024-12-04 06:40 UTC, MasterSkepticista commented
Turns out I confused `log_metric` and `log.metric` in one of the previous PRs, which led to it being removed, giving an impression of dead code.

I have restored TB support and added missing function calls. With this, gramine-based runs fail, probably because python multiprocessing is not supported by gramine. What do you suggest?

2024-12-04 09:20 UTC, theakshaypant commented on setup.py
>      install_requires=[
Some of the minimum version requirements are explicitly mentioned due to SDL requirements. I think we should keep those.

2024-12-04 12:47 UTC, MasterSkepticista commented on setup.py
>      install_requires=[
Could you mention which, specifically?

2024-12-04 13:51 UTC, MasterSkepticista commented on openfl/component/aggregator/aggregator.py
These have been reverted.

2024-12-04 17:01 UTC, merged

2024-12-05 04:08 UTC, theakshaypant commented on setup.py
>      install_requires=[
`requests>=2.32.0` is one that I can remember on top of my head; but sure, we can create separate PRs for those as required.