[Please Don't Merge] implement a new ModeBasedAssigner for FedEval
intel/openfl pull request #1226
Opened 2024-12-23 04:25 UTC by ishaileshpant

- implement a new ModeBasedAssigner class extending RandomGroupedAssigner
- update defaults/assigner.yaml to use ModeBasedAssigner with default mode to train_and_validate
- update fedeval sample workspace to use default assigner, tasks and aggregator

- [ ] Testcases for ModeBasedAssigner
- [ ] Testing for all existing workspaces
- [ ] Change all workspaces to use new Assigner
- [ ] Documentation update

2025-01-06 14:38 UTC, teoparvanov reviewed
Hi @ishaileshpant, it looks good - here are some thoughts and comments from my first read-through

2025-01-06 14:38 UTC, teoparvanov commented on openfl/component/assigner/mode_based_assigner.py
> +            Post filtering it deletgates the task assignment to RandomGroupedAssigner.
Why not keep it simple, and just have this in the docstring:
```
    Given a set of task groups and mode it filters the task groups based
    on mode. It futher enforces checks for specific modes.
    Post filtering it deletgates the task assignment to RandomGroupedAssigner.
```

2025-01-06 14:38 UTC, teoparvanov commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
Why extending the `RandomGroupedAssigner` specifically? Wouldn't mode switching also be applicable to `StaticGroupedAssigner` (among other possible implementations)?

Alternatively you could consider implementing the `ModeBasedAssigner` as a decorator for `define_task_assignments()` ?

2025-01-06 14:38 UTC, teoparvanov commented on tests/openfl/component/assigner/test_mode_based_assigner.py
> +    task_groups = [{"name": "train", "tasks": ["task1"], "percentage": 1.0}]
nit: `task_groups` -> `training_task_groups`

2025-01-06 14:38 UTC, teoparvanov commented on tests/openfl/component/assigner/test_mode_based_assigner.py
> +        {"name": "random-mode", "tasks": ["task4"], "percentage": 1.0}
`"train-and-validate"` maybe?

2025-01-06 15:27 UTC, ishaileshpant commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
This was based on all the current workspaces using RandomGroupAssigner and to ensure backward compat thought of extending it minimizing impacts on existing workspace

2025-01-06 23:29 UTC, kta-intel reviewed
Thanks @ishaileshpant! This is good foundation. Overall, I like the idea of distributing the modes as separate task groups and letting the assigner distribute them as appropriate. I have two comments for discussion.

2025-01-06 23:29 UTC, kta-intel commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
> This was based on all the current workspaces using RandomGroupAssigner and to ensure backward compat thought of extending it minimizing impacts on existing workspace

That reasoning makes sense regarding minimizing impact; however, I imagine that we want the ability to select the mode for any subclass of `Assigner`. Is it possible to move this logic to the base class `Assigner` instead?

2025-01-06 23:29 UTC, kta-intel commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
Correct me if I am wrong, but it seems like this would still require a user to redistribute the plan if they wanted to run federated evaluation. There is nothing inherently wrong with this, of course, but I don't think it quite grants the ability for a user to seamlessly switch between modes. In fact, wouldn't they still require two separate plans/workspaces?

2025-01-07 07:03 UTC, ishaileshpant commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
Agree seems like we need to pull this out of plan itself, possibly aggregator as suggested by @psfoley would be the best place without changing plan across different runs.
the only doubt I have is afaiu its generally different set of collaborators that do training than ones that will do validations - for that purpose anyways it's a different federation run with plan mode change and wouldn't that mandate a plan distribution?

2025-01-07 07:04 UTC, ishaileshpant commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
Moving to Assigner level makes a lot of sense to me

2025-01-07 08:12 UTC, ishaileshpant commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
On second thought - Assigner work on tasks rather the task_groups and the filtering is based on group_name not task name - this gives flexibility, even beyond the default tasks, to filter based on group name instead of task name

2025-01-07 20:19 UTC, kta-intel commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
> Assigner work on tasks rather the task_groups and the filtering is based on group_name not task name

Oh, this is true. Good point. 

A follow up question is that `mode` appears directly tied to the `task_group.name` with the primary added feature being that it'll assert that the rounds be set to 1 if in evaluation mode. If this is the case, do you think it would be better to implement this filtering logic directly into `RandomGroupedAssigner` (and the other assigners) rather than creating a separate class? I am still mainly echoing Teo's sentiment that mode switching should be applicable to all assigners

2025-01-07 20:51 UTC, kta-intel commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
> Agree seems like we need to pull this out of plan itself, possibly aggregator as suggested by @psfoley would be the best place without changing plan across different runs.

Agreed, this is also the direction I am leaning. My open question here is how to signal to the collaborators that the experiment is starting in evaluation mode since there's a huge difference in commitment between full training and a single evaluation round. 

Maybe I am overthinking this, though, since you bring up a good point in your second point:

> the only doubt I have is afaiu its generally different set of collaborators that do training than ones that will do validations - for that purpose anyways it's a different federation run with plan mode change and wouldn't that mandate a plan distribution?

This is correct intuition, and the current assigners do actually support assigning individual collaborators (statically or randomly) to a task group [[ref](https://github.com/securefederatedai/openfl/blob/develop/openfl/component/assigner/assigner.py#L66)]. So you could have a set of collaborators dedicated entirely to evaluation within the same plan without redistribution,. Afaiu, the biggest caveat is that they perform their tasks alongside the "training" group instead of in a separate run, but I think having a mode switching feature that is triggered outside the plan may potentially resolve this. However, for this to work, I think you would need to able to allow an experiment to start once the subset of collaborators for that task mode are online rather than once all registered participants are online.

2025-01-08 04:58 UTC, ishaileshpant commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
@kta-intel @teoparvanov i've refactored this to use decorator mode_based_filtering and all those sub-classes which has task_groups to leverage the decorator
removed new class and its test cases

2025-01-08 07:34 UTC, ishaileshpant commented on openfl/component/assigner/assigner.py
> +                    logger.warning(
@teoparvanov @kta-intel int this edge case should we err or warn 
line 138 errs post filtering if task groups are empty - these two behaviors are contradictory?

2025-01-08 08:48 UTC, ishaileshpant commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
another point is number_of_rounds - for training it most probably will be >1 but for evaluate we (as of now) only err in case its higher and mandate a manual change to 1 - think while we are at it we should potentially ignore round_number as set it to 1 cause if we don't - it again mandates plan change b/w train and evaluate run

2025-01-08 15:05 UTC, teoparvanov commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
Nice work adding the decorator, @ishaileshpant ! Just wondering though, why remove the test? Isn't it still possible to test the `RandomGroupedAssigner`, even though internally it uses a decorator now?

2025-01-08 15:09 UTC, teoparvanov commented on openfl/component/assigner/assigner.py
> +                    logger.warning(
I suggest to "fail fast" in such cases, and raise an error, as on line 138. You could do so via an assertion, instead of a `ValueError` - see my comment below.

2025-01-08 15:12 UTC, teoparvanov commented on openfl/component/assigner/assigner.py
> +                    raise ValueError(f"No task groups found after filtering for mode: {self.mode}")
nit - this isn't really a value error, but more of an invariant breach, so I'd suggest refactoring it as an assertion:

```python
assert self.task_groups, f"No task groups found after filtering for mode: {self.mode}"
```

2025-01-08 15:16 UTC, teoparvanov commented on openfl/component/assigner/random_grouped_assigner.py
>      def define_task_assignments(self):
If you imported the `mode_based_filtering` symbol separately, you could simply write:
```python
@mode_based_filtering
    def define_task_assignments(self):
        ...
```

2025-01-08 15:16 UTC, teoparvanov commented on openfl/component/assigner/static_grouped_assigner.py
> +    @Assigner.mode_based_filtering
same here?

2025-01-08 15:24 UTC, teoparvanov commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
I'd also be in favor of adding mode switching at the aggregator level (via `fx aggregator` command f.e.), in addition to the setting in the FL plan. This, however, can be implemented in a separate PR IMO.

2025-01-08 17:18 UTC, ishaileshpant commented on openfl/component/assigner/mode_based_assigner.py
> +class ModeBasedAssigner(RandomGroupedAssigner):
yeah i am adding them to assigner existing test cases file so remove the existing one

2025-01-08 17:19 UTC, ishaileshpant commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
Already on it

2025-01-08 17:21 UTC, ishaileshpant commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
The only concern i have with overriding without changing the plan is that plan hash, which afaiu, goes into aggregator uuid as well, will not be representative of the actual running plan - but i agree its not a security risk, just a little delecting

2025-01-10 13:54 UTC, MasterSkepticista reviewed
It is not quite clear to me, the need for a new task group and the associated machinery. I will lay my understanding, please help me understand what is this PR solving that the current design does not support.

This is what is supplied in a plan today:

```yaml
task_groups  :
    - name       : train_and_validate
      percentage : 1.0
      tasks      :
        - aggregated_model_validation
        - train
        - locally_tuned_model_validation
```

Questions:
1. Why is it not sufficient for a user to simply provide `aggregated_model_validation` task?
  ```yaml
    task_groups  :
      - name       : validate
        percentage : 1.0
        tasks      :
          - aggregated_model_validation
  ```
2. Per my understanding, the `name: train_and_validate` is for the user's convenience, and could be anything. OpenFL does not make any internal decisions based on a task group "name".
3. Which brings me to the confusion behind creating `name: evaluate` task group, and all the gymnastics being done around it in this PR.

2025-01-10 14:55 UTC, ishaileshpant commented
> It is not quite clear to me, the need for a new task group and the associated machinery. I will lay my understanding, please help me understand what is this PR solving that the current design does not support.
The new task group name is to ensure that we have clear demarcation between train (or train_and_validate) and evaluation /evaluate type of tasks to disambiguate the two - validate vs evaluate

2025-01-10 14:58 UTC, ishaileshpant commented
> Questions:
> 
> 1. Why is it not sufficient for a user to simply provide `aggregated_model_validation` task?
> 
> ```yaml
>   task_groups  :
>     - name       : validate
>       percentage : 1.0
>       tasks      :
>         - aggregated_model_validation

Thats exactly what we have done in the defaults tasks yaml - defined both the task groups and then using mode as a filter b/w training and evaluate run using the same plan without mutating the plan or needing a different plan or needing any manual changes to plan to run in train or evaluate mode

This PR though expose the mode field at assigner level but eventually as per the PR #1258 this will be dictated by Aggregator without the need to change the plan yaml b/w training and evaluate run

2025-01-10 15:04 UTC, ishaileshpant commented
>Per my understanding, the name: train_and_validate is for the user's convenience, and could be anything. OpenFL does not make any internal decisions based on a task group "name".

well this is true as per the current design/implementation and that's exactly what we are trying to extend by using group name as the driver - i agree we can do better naming or may be define a new attribute to link the mode to - in spirit of keeping the changes to minimal and still give a better UX to use the same plan for train and validate, existing task_group.name could be best place to map the mode to

If we don't explicitly do valid mode checks (Please see #1258) then we can make it flexible enough for user to define any task_group name of their choice and basically leverage this design further without needing a code change for new task_groups if needed in future

2025-01-11 06:26 UTC, MasterSkepticista commented
> If we don't explicitly do valid mode checks (Please see https://github.com/securefederatedai/openfl/pull/1258) then we can make it flexible enough for user to define any task_group name of their choice and basically leverage this design further without needing a code change for new task_groups if needed in future

I prefer this because eval is a problem of task group switching (in essence FedEval vs FedTrain is a "selection" problem, not one of "filtering", correct?).

Training a model is a task, evaluation is a task, perhaps purging and regeneration of cryptography keys is a task (@theakshaypant)? These tasks would be defined beforehand in the plan. OpenFL will verify if the requested task name matches one of the specified ones in the plan. But that is all to it; no "filtering" or modification of assigner code is (or needs to be) necessary IMO.

All that I care as a user, is to be able to select what I want to run from the aggregator side. A user wouldn't be happy if a framework requires them to dig into the source code to add a new task with brand-new `if-else` statements.

Documented an example here: https://github.com/securefederatedai/openfl/pull/1258#discussion_r1911907837 WDYT?

2025-01-11 08:03 UTC, ishaileshpant commented
> I prefer this because eval is a problem of task group switching (in essence FedEval vs FedTrain is a "selection" problem, not one of "filtering", correct?).

Selection or filtering they are two ways of saying / doing the same thing IMO :), nevertheless with mode/task/task-group being supplied at aggregator level still needs to be passed to assigner cause that's where we have logic for task group parsing and task assignments and is rightly placed. 

We just need to leverage the same to decide which is the task-group of interest to the assigner as per the aggregator mode

> All that I care as a user, is to be able to select what I want to run from the aggregator side. A user wouldn't be happy if a framework requires them to dig into the source code to add a new task with brand-new `if-else` statements.

Well there is no if-else as of now and IDT will need in future as well except the task-group.name comparison to mode. Now we rename that to --task or better yet task-group nevertheless we still need the check, that way the default assigner can simply have all task-groups and aggregator decides which one is of interest in a specific federation run 

The only thing I feel we need to pull out of this PR and push to aggregator level is the mode/task-group based validation checks - e.g for task-group.name=evaluation we need to enforce round_number to 1 and this, in hindsight, is not rightly placed in assigner but aggregator. I will pull this out of this PR and move to #1258 

@psfoley Does this make sense?

2025-01-13 06:25 UTC, ishaileshpant commented on openfl-workspace/torch_cnn_mnist_fed_eval/plan/plan.yaml
> +    mode : evaluate
@kta-intel @teoparvanov please see #1258 where this mode (or selected-task-group) attribute is driven by Aggregator cli and leveraged by assigner to filter out other tasks groups other then selected task group for assignment to collaborators, once that is approved and merged will rebase this and align with name changes

2025-01-21 15:42 UTC, ishaileshpant commented on openfl/component/assigner/assigner.py
> +                    logger.warning(
Done

2025-01-21 15:42 UTC, ishaileshpant commented on openfl/component/assigner/assigner.py
> +                    raise ValueError(f"No task groups found after filtering for mode: {self.mode}")
Done

2025-01-21 16:01 UTC, ishaileshpant commented on openfl/component/assigner/random_grouped_assigner.py
>      def define_task_assignments(self):
Done

2025-01-21 16:01 UTC, ishaileshpant commented on openfl/component/assigner/static_grouped_assigner.py
> +    @Assigner.mode_based_filtering
Done

2025-01-24 10:43 UTC, teoparvanov approved these changes
Nice work, @ishaileshpant, I think it's looking good at this stage!

2025-01-24 10:43 UTC, teoparvanov commented on tests/openfl/component/assigner/test_random_grouped_assigner.py
> +#     assert tasks == task_groups[1]['tasks']
Is this test disabled on purpose?

2025-01-24 10:43 UTC, teoparvanov commented on tests/openfl/component/assigner/test_assigner.py
> +    assert assigner.selected_task_group == 'learning'
For completeness, could you also add a unit test where `assigner.selected_task_group == 'evaluation'`?

2025-01-24 10:43 UTC, teoparvanov commented on openfl/component/assigner/static_grouped_assigner.py
>      def define_task_assignments(self):
I suggest renaming the decorator to `@with_selected_task_groups`. This way the code "reads" almost like in English: "With the selected task groups, define the task assignments...". WDYT?

2025-01-24 13:15 UTC, tanwarsh approved these changes

2025-01-24 13:25 UTC, rahulga1 approved these changes
LGTM, just modify based on Teo's suggestions.

2025-01-28 01:03 UTC, psfoley requested changes
Thanks for the PR, @ishaileshpant. The scenario of multiple user defined task groups needs to be considered before this can be approved. Details are provided in the comments. I can go into more depth on the Assigner design during our standup as well.

2025-01-28 01:03 UTC, psfoley commented on openfl-workspace/workspace/plan/defaults/assigner.yaml
> +        - aggregated_model_validation
I need to provide some additional context here because this is not how the assigner is supposed to work. Most of the existing examples illustrate the simplest scenario (my fault) where all participants are allocated to a single task group. The RandomGroupedAssigner is really intended for scenarios when collaborators should be placed in _different_ task groups for a given round. The original definition of Federated Averaging called for a small subset of collaborators to be training for a given round, and a much larger set to be performing validation / evaluation. This was done as part of the FeTS Initiative. This allows collaborators to contribute to the final model, but allows computational resources / time to be saved for the totality of the federation. The percentage *_across_* task groups should sum to 1.0 (representing 100% of collaborators), not be set to 1.0 for each task group. An example is "evaluation" percentage set to 0.8 (80% performing validation / evaluation for each round), and "learning" percentage set to 0.2 (20% performing all learning related tasks for a round). If I'm reading the code correctly, the reason you're not running into this problem is you've set the "learning" task group as the default parameter. What should be done instead if you want to filter by task group is to shift the percentage for each task group *and* alert users in some way that this has been done / is a permitted change in the plan. Instead of having a default task group at all, this can be achieved by having multiple task groups in the way you have here, but setting the learning task_group to `1.0`, and evaluation to `0.0`. When the evaluation task group is specified from command line this can shift to learning percentage '0.0', and evaluation percentage `1.0`. This way users will still be able to define multiple task groups to run within a single federation.

2025-01-28 01:03 UTC, psfoley commented on openfl/component/assigner/assigner.py
> +        selected_task_group: str = "learning",
See comment as above - we should not have a default task group. This will override user's configuration in the case that multiple task groups are set in the plan. The right way to make this the default is the default plan learning task group set to 1.0 and others (i.e. evaluation) set to 0.0

2025-01-28 11:04 UTC, payalcha commented on openfl-workspace/workspace/plan/defaults/assigner.yaml
> +        - aggregated_model_validation
@psfoley - In case of multiple task-groups for e.g learning and evaluation in same plan.yaml. How the run will behave.

2025-01-28 11:07 UTC, payalcha commented on openfl/component/aggregator/aggregator.py
> +            self.rounds_to_train = 1
We don't need to modify rounds_to_train in  plan.yaml post this changes. 
Aggregator will take care of the modification.

2025-01-28 11:09 UTC, payalcha commented on openfl/component/assigner/assigner.py
> +        selected_task_group: str = "learning",
Does this means that multiple task-groups can be processed in the same experiment?
Currently all examples have only task-group running.
Do we have any example or use-case in which we can see that multiple task-groups running in same experiment.

2025-01-30 00:59 UTC, psfoley commented on openfl/component/assigner/assigner.py
> +                    group for group in self.task_groups if group["name"] == self.selected_task_group
What happens if someone accidentally / purposefully lists "learning" or "evaluation" twice?

2025-01-30 01:00 UTC, psfoley commented on openfl/component/assigner/assigner.py
> +                    group for group in self.task_groups if group["name"] == self.selected_task_group
Nevermind! I see this is handled

2025-01-30 01:02 UTC, psfoley approved these changes

2025-01-30 06:58 UTC, ishaileshpant commented
@kta-intel for the last task as discussed in #1258 i've created an issue #1321 and will track that fix via that

2025-01-30 07:00 UTC, merged