Implement unbalanced dataset splits
intel/openfl pull request #125
Opened 2021-07-15 13:54 UTC by itrushkin

2021-07-23 08:06 UTC, itrushkin commented
Should be merged after #104.

2021-08-03 21:02 UTC, igor-davidyuk requested changes
Please fix the integration to the shard_descriptor part.

2021-08-03 21:02 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/Director_Pytorch_Kvasir_UNET/envoy_folder/kvasir_shard_descriptor.py
> +class KvasirDataset(Dataset):
There is no need in pytorch dataset here. I suggest removing all pytorch mentions

2021-08-03 21:02 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/Director_Pytorch_Kvasir_UNET/envoy_folder/kvasir_shard_descriptor.py
> +        self.shard = Subset(dataset, shard_idx)
this line could be just 
`self.images_names = [self.images_names[i] for i in shard_idx]`

2021-08-03 21:02 UTC, igor-davidyuk commented on openfl/plugins/data_splitters/numpy.py
> +    def split(self, labels, num_collaborators):
seems like the signature is changed in this subclass

2021-08-04 18:41 UTC, igor-davidyuk approved these changes
Looks good to me!

2021-08-13 14:18 UTC, aleksandr-mokrov approved these changes

2021-08-25 07:03 UTC, itrushkin commented
Jenkins please retry a build

2021-08-25 07:24 UTC, itrushkin commented
Jenkins please retry a build

2021-08-25 12:00 UTC, itrushkin commented
Jenkins please retry a build

2021-08-25 14:24 UTC, merged