FedProx implementation for Adam optimizer
intel/openfl pull request #127
Opened 2021-07-27 13:43 UTC by maradionov

2021-07-28 14:14 UTC, itrushkin requested changes

2021-07-28 14:14 UTC, itrushkin commented on openfl/utilities/optimizers/torch/fedprox.py
> +class AdamProx(Optimizer):
Since we consider it as FedProx version of Adam optimizer, I would suggest keeping the `FedProx` and naming it `FedProxAdam`.

2021-07-28 14:14 UTC, itrushkin commented on openfl/utilities/optimizers/torch/fedprox.py
> +            param.addcdiv_(exp_avg, denom, value=-step_size)
Newline at end of file

2021-07-28 14:14 UTC, itrushkin commented on openfl-tutorials/Federated_AdamProx_PyTorch_MNIST_Tutorial.ipynb
> +    "from tensorflow.keras.utils import to_categorical\n",
Executing these lines will raise an error in an empty environment because TensorFlow is not installed in the `torch_cnn_mnist` workspace template. Please consider using MNIST from `torchvision.datasets` as we do it in the PyTorch MNIST and FedProx notebooks.

2021-07-28 14:14 UTC, itrushkin commented on openfl-tutorials/Federated_AdamProx_PyTorch_MNIST_Tutorial.ipynb
> +    "class Net(nn.Module):\n",
Network class should be defined in a separate cell

2021-07-28 14:14 UTC, itrushkin commented on openfl-tutorials/Federated_AdamProx_PyTorch_MNIST_Tutorial.ipynb
> +     ]
Clear cell output

2021-07-28 14:14 UTC, itrushkin commented on openfl-tutorials/Federated_AdamProx_PyTorch_MNIST_Tutorial.ipynb
> +      "text/plain": [
Clear cell output

2021-07-28 14:14 UTC, itrushkin commented on openfl/utilities/optimizers/torch/fedprox.py
> +class AdamProx(Optimizer):
Can we inherit from `Adam` PyTorch optimizer class to avoid copying of shared code?

2021-07-28 14:14 UTC, itrushkin commented on openfl-tutorials/Federated_AdamProx_PyTorch_MNIST_Tutorial.ipynb
> +   "outputs": [
Clear cell output

2021-07-30 13:28 UTC, itrushkin commented on openfl-tutorials/Federated_AdamProx_PyTorch_MNIST_Tutorial.ipynb
> +    "# Federated AdamProx PyTorch MNIST Tutorial\n",
```suggestion
    "# Federated FedProxAdam PyTorch MNIST Tutorial\n",

2021-07-30 13:29 UTC, itrushkin commented on openfl-tutorials/Federated_AdamProx_PyTorch_MNIST_Tutorial.ipynb
> +    "# Federated AdamProx PyTorch MNIST Tutorial\n",
Notebook should also be renamed

2021-08-04 08:44 UTC, itrushkin approved these changes

2021-09-01 08:53 UTC, alexey-gruzdev commented
@itrushkin could we add this to existing FedProx notebook, rather than creating a new one?

2021-09-02 17:10 UTC, itrushkin commented
Jenkins please retry a build

2021-09-03 12:14 UTC, aleksandr-mokrov approved these changes

2021-09-03 12:15 UTC, merged