Change variable disable_tls to tls to avoid twice no like "if not dis…
intel/openfl pull request #133
Opened 2021-08-02 13:38 UTC by aleksandr-mokrov

Variable `disable_tls` was renamed to `tls` to avoid twice no like "if not disable_tls".
For CLI command it is possible to use the same old flag `--disable-tls` to disable mTLS.

2021-08-02 17:34 UTC, psfoley commented on openfl/interface/director.py
> +@option('--tls/--disable-tls', default=True,
This should just be `--tls`

2021-08-02 17:34 UTC, psfoley commented on openfl/interface/envoy.py
> +@option('--tls/--disable-tls', default=True,
Same comment as above. This should just be `@option('--tls', default=True,`

2021-08-02 17:36 UTC, psfoley requested changes
The changes are self explanatory. Once my two comments are addressed, I think this is ready for merge.

2021-08-02 18:05 UTC, aleksandr-mokrov commented on openfl/interface/director.py
> +@option('--tls/--disable-tls', default=True,
By default you can use `fx director start`  without TLS flag and variable `tls` will be set to `True`. But if you want to disable TLS, you can use `fx director start --disable-tls` and variable `tls` will be set to `False`. In other words, we disable mTLS only by explicitly passing the corresponding flag, by default mTLS is enabled.
[Click boolean flags specification](https://click.palletsprojects.com/en/8.0.x/options/#boolean-flags)

2021-08-03 16:36 UTC, igor-davidyuk approved these changes
seems legit

2021-08-03 16:51 UTC, psfoley approved these changes
Comments wer addressed. PR is approved.

2021-08-03 16:51 UTC, merged