WIP: Python current work directory no longer changes when starting and stopping aggregator and collaborator
intel/openfl pull request #140
Opened 2021-08-04 21:29 UTC by aleksandr-mokrov

Change working dir structure (client_id was added to path).
An opportunity to pass working directory path to aggregator and collaborator was added.
Python current work directory no longer changes when starting and stopping aggregator and collaborator form director and envoy.
Collaborator working directory creation was moved from director_client to envoy.

2021-08-05 04:38 UTC, igor-davidyuk requested changes

2021-08-05 04:38 UTC, igor-davidyuk commented on openfl/component/director/director.py
> +                'client_id': sender_name
Don't we disclose the experiment owner's identity to envoys here? Is it necessary?

2021-08-05 04:38 UTC, igor-davidyuk commented on openfl/component/director/director.py
> +        experiment_work_dir = Path(f'{os.getcwd()}/{sender_name}/{experiment_name}')
We discussed making timestamps-names for experiment working directories, is it a better idea?

2021-08-05 04:38 UTC, igor-davidyuk commented on openfl/component/envoy/envoy.py
> +                experiment_name, client_id = self.director_client.wait_experiment()
experiment owner's id on envvoys side, is it really needed?

2021-08-05 04:38 UTC, igor-davidyuk commented on openfl/component/envoy/envoy.py
> +                self.create_workspace(experiment_name, experiment_work_dir, data_stream)
This is a strange signature for the `create_workspace` method. Why it accepts data_stream? Its only responsibility should be to create the workspace, not reading the stream.

2021-08-05 04:38 UTC, igor-davidyuk commented on openfl/component/envoy/envoy.py
> +    def create_workspace(experiment_name, experiment_work_dir, response_iter):
Again, we have this functionality in three places: Director, Envoy, and the old CLI's `workspace import`.
We may think of creating one helper function and use it everywhere.

2021-08-05 04:38 UTC, igor-davidyuk commented on openfl/component/envoy/envoy.py
> +            attempts = 3
a hardcoded variable.

2021-08-05 04:38 UTC, igor-davidyuk commented on openfl/federated/plan/plan.py
> +              working_dir: Path = None):
It feels like we are polluting the Plan's code with folder management.
We removed two `os.chdir()` lines and then created like 150 more.

2021-08-06 10:54 UTC, dmitryagapov commented on openfl/component/director/director.py
> +        experiment_work_dir = Path(f'{os.getcwd()}/{sender_name}/{experiment_name}')
Maybe we can create constant path to save experiments data, e.g. `~/.openfl/experiments/`?

2021-08-06 15:44 UTC, closed without merging