FedCurv algorithm
intel/openfl pull request #167
Opened 2021-09-02 15:01 UTC by itrushkin

Implements "Federated Curvature" algorithm from paper: [Overcoming Forgetting in Federated Learning on
Non-IID Data](https://arxiv.org/pdf/1910.07796.pdf).
Closes #66.

2021-09-10 20:43 UTC, itrushkin commented
[TensorBoard](https://tensorboard.dev/experiment/BEW8JXRQQKOROLR9zXNZgQ/)

2021-09-10 20:44 UTC, itrushkin commented
Jenkins please retry a build

2022-02-18 13:47 UTC, alexey-khorkin commented on openfl/utilities/fedcurv/torch/fedcurv.py
> +        precision_matrices = {n: p for n, p in precision_matrices.items()}
Is this line of code really necessary?

2022-02-22 18:52 UTC, dmitryagapov requested changes

2022-02-22 18:52 UTC, dmitryagapov commented on openfl-tutorials/interactive_api/PyTorch_FedCurv/envoy/tinyimagenet_shard_descriptor.py
> +        self._data_folder = os.path.join(data_folder, data_type)
```suggestion
        self._data_folder = data_folder / data_type
```

2022-02-22 18:52 UTC, dmitryagapov commented on openfl-tutorials/interactive_api/PyTorch_FedCurv/envoy/tinyimagenet_shard_descriptor.py
> +                os.path.join(self._data_folder, '**', '*.JPEG'),
```suggestion
                str(self._data_folder / '**' / '*.JPEG'),
```

2022-02-22 18:52 UTC, dmitryagapov commented on openfl-tutorials/interactive_api/PyTorch_FedCurv/envoy/tinyimagenet_shard_descriptor.py
> +        with open(os.path.join(self._common_data_folder, 'wnids.txt'), 'r') as fp:
```suggestion
        with open(self._common_data_folder / 'wnids.txt', 'r') as fp:
```

2022-02-22 18:52 UTC, dmitryagapov commented on openfl/utilities/fedcurv/aggregation_function.py
> +            with open(Path('~').expanduser() / 'fedcurv_log.txt', 'a') as f:
If `Path('~').expanduser()` user's home direcory maybe better to use `Path.home()`

2022-02-28 09:07 UTC, dmitryagapov requested changes

2022-02-28 09:07 UTC, dmitryagapov commented on openfl/utilities/fedcurv/torch/fedcurv.py
> +                    with open(Path('~').expanduser() / 'fedcurv_log.txt', 'a') as f:
`Path('~').expanduser()` -> `Path.home()`

2022-02-28 18:02 UTC, alexey-khorkin commented on openfl/utilities/fedcurv/torch/__init__.py
> +"""openfl.utilities.fedcurv.torch package."""
Should we add corporation comments?
```suggestion
# Copyright (C) 2021-2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
"""openfl.utilities.fedcurv.torch package."""
```

2022-02-28 18:13 UTC, alexey-khorkin commented on openfl/utilities/fedcurv/aggregation_function.py
> +"""FedCurv Aggregation function module."""
Should we replace this module to https://github.com/intel/openfl/tree/develop/openfl/component/aggregation_functions and rename it to `fedcurv_aggregation.py` ?

2022-02-28 18:15 UTC, itrushkin commented
Experiments results:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/76161256/156035817-454c70ed-f54c-4204-acab-ecab64b2731c.png">
Graphs show that FedCurv with lambda equal to 10 performs better than FedAvg in terms of accuracy, and some other lambda values (1000, 10000000).

2022-02-28 18:18 UTC, alexey-khorkin commented
> Experiments results: <img alt="image" width="1422" src="https://user-images.githubusercontent.com/76161256/156035817-454c70ed-f54c-4204-acab-ecab64b2731c.png"> Graphs show that FedCurv with lambda equal to 10 performs better than FedAvg in terms of accuracy, and some other lambda values (1000, 10000000).
@itrushkin 
Is `histology_test_experiment` the FedAvg setup?

2022-02-28 18:21 UTC, itrushkin commented
> > Experiments results: <img alt="image" width="1422" src="https://user-images.githubusercontent.com/76161256/156035817-454c70ed-f54c-4204-acab-ecab64b2731c.png"> Graphs show that FedCurv with lambda equal to 10 performs better than FedAvg in terms of accuracy, and some other lambda values (1000, 10000000).
> > @itrushkin
> > Is `histology_test_experiment` the FedAvg setup?

@alexey-khorkin Yes, correct. Perhaps the difference could be much more visible with rounds increasing.

2022-03-01 12:06 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/histology_shard_descriptor.py
> +    DEFAULT_PATH = Path.home() / '.openfl' / 'data'
Try to avoid using folders outside the current workspace. The default data location for envoy is ./data

2022-03-01 12:08 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/histology_shard_descriptor.py
> +        root = root.expanduser()
```suggestion
        root = root.absolute()
```

2022-03-01 12:08 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/histology_shard_descriptor.py
> +    DEFAULT_PATH = Path.home() / '.openfl' / 'data'
```suggestion
    DEFAULT_PATH = Path('.') / 'data'
```

2022-03-01 12:17 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/histology_shard_descriptor.py
> +            target_dir = os.path.join(root, target_class)
You are already using pathlib, os.path is redundant

2022-03-01 12:17 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/histology_shard_descriptor.py
> +            target_dir = os.path.join(root, target_class)
```suggestion
            target_dir = root / target_class
```

2022-03-01 12:17 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/histology_shard_descriptor.py
> +            for class_root, _, fnames in sorted(os.walk(target_dir, followlinks=True)):
may be we can use Path.glob() here

2022-03-01 12:17 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/populate_envoys.sh
> +" > $i/envoy_config.yaml
well done 👍

2022-03-01 13:04 UTC, igor-davidyuk approved these changes
Please make sure data is downloaded and used correctly with a new path

2022-03-01 13:24 UTC, dmitryagapov approved these changes

2022-03-01 13:34 UTC, aleksandr-mokrov approved these changes

2022-03-01 13:35 UTC, alexey-gruzdev commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/envoy/populate_envoys.sh
> +    echo "fx envoy start -n env_$i --disable-tls --envoy-config-path envoy_config.yaml -dh nnlicv431.inn.intel.com -dp 50053" > $i/start_envoy.sh
Can we parametrize `-dh nnlicv431.inn.intel.com -dp 50053` with variables, and maybe insert everywhere `localhost`?

2022-03-01 13:36 UTC, itrushkin commented
@igor-davidyuk Re-launched experiment and data is being split and loaded properly.

2022-03-01 13:36 UTC, alexey-gruzdev commented on openfl-tutorials/interactive_api/PyTorch_Histology_FedCurv/README.md
> +jupyter notebook
`jupyter lab pytorch_histology.ipynb`?

2022-03-01 16:27 UTC, alexey-gruzdev approved these changes

2022-03-01 16:27 UTC, merged