Remove sh tutorial scripts
intel/openfl pull request #205
Opened 2021-10-08 14:26 UTC by alexey-khorkin

This pull request is to remove all `.sh` files and replace them with readme files with detailed instructions on how to start the experiment with or without TLS.

2021-10-11 09:56 UTC, dmitryagapov requested changes

2021-10-11 09:56 UTC, dmitryagapov commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/README.md
> +Optional: start second envoy:
This string looks strange

2021-10-11 09:56 UTC, dmitryagapov commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/README.md
> +<img src="https://production-media.paperswithcode.com/datasets/Market-1501-0000000097-a728ab2d_gyNBlrI.jpg" alt="alt text" width="400" height="whatever">
`alt="alt text"` and `height="whatever"` could be deleted

2021-10-11 09:56 UTC, dmitryagapov commented on openfl-tutorials/interactive_api/PyTorch_TinyImageNet/README.md
> +<img src="https://production-media.paperswithcode.com/datasets/Tiny_ImageNet-0000001404-a53923c3_XCrVSGm.jpg" alt="alt text" width="500" height="whatever">
`alt="alt text"` and `height="whatever"` could be deleted

2021-10-11 09:56 UTC, dmitryagapov commented on openfl-tutorials/interactive_api/Tensorflow_MNIST/README.md
> +<img src="http://i.ytimg.com/vi/0QI3xgXuB-Q/hqdefault.jpg" alt="alt text" width="whatever" height="whatever">
`alt="alt text"`, `width="whatever"` and `height="whatever"` could be deleted

2021-10-11 10:00 UTC, dmitryagapov commented
It would be great if we stopped using `jupyter notebook` and start using `jupyter lab` everywhere.

2021-10-11 10:01 UTC, dmitryagapov commented
Should we add to `README.md` instruction for `tls` case?

2021-10-11 10:11 UTC, alexey-gruzdev commented
> It would be great if we stopped using `jupyter notebook` and start using `jupyter lab` everywhere.

In that case, I believe we need to correct https://github.com/intel/openfl/blob/develop/setup.py#L66 to install lab with installation of OpenFL.

2021-10-11 10:16 UTC, alexey-gruzdev commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/README.md
> +Optional: start second envoy:
Agree, let's add second  '.yaml' config and use second envoy as well. Not optional step

2021-10-11 10:17 UTC, alexey-gruzdev commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/README.md
> +### 3. How to run this tutorial (without TLC and locally as a simulation):
Why we have missing step 2.?

2021-10-11 10:20 UTC, alexey-gruzdev commented
> Should we add to `README.md` instruction for `tls` case?

I would agree here. I believe it would be great to have a `tls` case, with steps for certificate generation too.

2021-10-11 10:22 UTC, alexey-gruzdev commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/README.md
> +### 2. How to run this tutorial (without TLC and locally as a simulation):
I would suggest to reformulate this, because we could simply replace `localhost` with real machine name and run in distributed manner, so it's not a big deal between local & distributed running. With or Without TLS - differs because of cert generation step.

2021-10-12 01:02 UTC, alexey-khorkin commented
@alexey-gruzdev , @dmitryagapov,  Should I create another one README file inside `interactive_api` folder with shared instruction about how to run one of examples?
Because now we have the same instruction inside all readme files (i mean - "How to run this tutorial" step)

2021-10-12 08:36 UTC, katerina-merkulova commented
@alexey-khorkin, Could you add `pip install -r requirements.txt` before starting each envoy?

2022-01-13 08:09 UTC, alexey-gruzdev commented
It was decided to not go with strategy to remove all `.sh` scripts and move completely to `fx` commands for user convenience (at least for right now).

2022-01-13 08:09 UTC, closed without merging