Build docker test errors
intel/openfl pull request #214
Opened 2021-10-20 13:45 UTC by aleksandr-mokrov

Added filtering of packages without version when exporting workspace (local packages are excluded).
Added docker build logging in case of a build error

2021-10-20 17:50 UTC, igor-davidyuk commented on openfl/interface/workspace.py
> +    except Exception as e:
could you please remove this last exception so we see the error traceback (or also print the traceback from here)

2021-10-20 17:51 UTC, igor-davidyuk approved these changes

2021-10-21 07:40 UTC, dmitryagapov commented on openfl/interface/workspace.py
>          echo('The workspace image has been built successfully!')
Maybe we should delete this `else` block and put it on the end of `try` block?

2021-10-21 08:28 UTC, itrushkin requested changes

2021-10-21 08:28 UTC, itrushkin commented on openfl/interface/workspace.py
> +    echo(f'!Workspace exported to archive: {archive_file_name}')
This change seems occasional.

2021-10-21 08:28 UTC, itrushkin commented on openfl/utilities/utils.py
> +def is_package_has_version(package: str) -> bool:
Function name has a grammatical mistake: in an interrogative sentence, the verb "have" must be used with the auxiliary verbs "do" or "does", not "is". 
Some correct versions of naming:
 - `is_package_versioned` - this one I like the most
 - `package_has_version`
 - `does_package_have_version`

2021-10-21 14:43 UTC, dmitryagapov commented on openfl/utilities/utils.py
> +def is_package_has_version(package: str) -> bool:
@itrushkin, I'm not argee with you. Generally all functions that checks smth and used in `if` statement started with `is_`.

2021-10-21 17:45 UTC, aleksandr-mokrov commented on openfl/interface/workspace.py
> +    except Exception as e:
removed

2021-10-21 17:46 UTC, aleksandr-mokrov commented on openfl/interface/workspace.py
>          echo('The workspace image has been built successfully!')
I put it after

2021-10-21 17:46 UTC, aleksandr-mokrov commented on openfl/interface/workspace.py
> +    echo(f'!Workspace exported to archive: {archive_file_name}')
fixed

2021-10-21 17:49 UTC, aleksandr-mokrov commented on openfl/utilities/utils.py
> +def is_package_has_version(package: str) -> bool:
renamed to is_package_versioned

2021-10-22 08:06 UTC, itrushkin approved these changes

2021-10-22 10:39 UTC, dmitryagapov approved these changes

2021-10-22 10:58 UTC, alexey-gruzdev commented
ok to test

2021-10-25 07:10 UTC, merged