Linear regression Example - custom numpy framework adapter
intel/openfl pull request #286
Opened 2021-12-28 08:54 UTC by igor-davidyuk

closes #267

2021-12-28 09:03 UTC, igor-davidyuk commented
I have read the CLA Document and I hereby sign the CLA

2022-01-18 07:03 UTC, itrushkin commented on openfl-tutorials/interactive_api/linear_regression/workspace/SingleNotebook.ipynb
> +    "!git clone https://github.com/igor-davidyuk/openfl.git -b linear-regression-numpy-tutorial\n",
This should be changed to original repository after merge.

2022-01-20 11:06 UTC, aleksandr-mokrov requested changes

2022-01-20 11:06 UTC, aleksandr-mokrov commented on openfl-tutorials/interactive_api/linear_regression/README.md
> +2. Follow `LinReg.ipynb` to train a simple model.
Missing launch information in colab (haw to launch and preparation steps)

2022-01-20 11:06 UTC, aleksandr-mokrov commented on openfl-tutorials/interactive_api/linear_regression/workspace/custom_adapter.py
> +    def __init__(self) -> None:
It's redundant, the same as in the parent class

2022-01-20 11:06 UTC, aleksandr-mokrov commented on openfl/component/envoy/envoy.py
> +                        self.name + ' ' + experiment_name,
Looks like the problem is not here, but in that you launch all envoys in one directory. By design they should have their own working directory, with their own config file, shard descriptor.

2022-01-20 11:06 UTC, aleksandr-mokrov commented on openfl-tutorials/interactive_api/linear_regression/workspace/LinReg.ipynb
> +    "![image.png](attachment:99c798ac-85a8-48d6-bb31-a76508d20063.png)"
This image is not displayed in colab. And, maybe we will not store the picture in the git?

2022-01-20 11:06 UTC, aleksandr-mokrov commented on openfl-tutorials/interactive_api/linear_regression/workspace/LinReg.ipynb
> +    "#Define input array with angles from 60deg to 300deg converted to radians\n",
#Define -> # Define

2022-01-20 11:06 UTC, aleksandr-mokrov commented on openfl-tutorials/interactive_api/linear_regression/workspace/LinReg.ipynb
> +    "np.random.seed(10)  #Setting seed for reproducibility\n",
#Setting -> # Setting

2022-01-20 11:06 UTC, aleksandr-mokrov commented on openfl-tutorials/interactive_api/linear_regression/workspace/SingleNotebook.ipynb
> +    "Using an Optimizer does not make sense for this experiment. Yet it is a required part of a trainingtask contract in current version of OpenFL, so we just pass None\n",
`trainingtask` -> `training task`, `None` -> `None.`

2022-01-20 11:22 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/linear_regression/workspace/custom_adapter.py
> +    def __init__(self) -> None:
removed, thanks

2022-01-20 11:23 UTC, igor-davidyuk commented on openfl/component/envoy/envoy.py
> +                        self.name + ' ' + experiment_name,
All our examples run envoys from a single workspace. I would say that it is a free feature.

2022-01-20 11:25 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/linear_regression/workspace/LinReg.ipynb
> +    "![image.png](attachment:99c798ac-85a8-48d6-bb31-a76508d20063.png)"
replaced the image with a link

2022-01-20 11:26 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/linear_regression/workspace/LinReg.ipynb
> +    "#Define input array with angles from 60deg to 300deg converted to radians\n",
fixed. thanks

2022-01-20 11:27 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/linear_regression/workspace/LinReg.ipynb
> +    "np.random.seed(10)  #Setting seed for reproducibility\n",
fixed

2022-01-20 11:28 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/linear_regression/workspace/SingleNotebook.ipynb
> +    "Using an Optimizer does not make sense for this experiment. Yet it is a required part of a trainingtask contract in current version of OpenFL, so we just pass None\n",
```suggestion
    "Using an Optimizer does not make sense for this experiment. Yet it is a required part of a training task contract in the current version of OpenFL, so we just pass None.\n",
```

2022-01-20 12:05 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/linear_regression/README.md
> +### Google Colab
```suggestion
### Google Colab:
```

2022-01-20 12:11 UTC, igor-davidyuk commented on openfl-tutorials/interactive_api/linear_regression/README.md
> +2. Follow `LinReg.ipynb` to train a simple model.
Extended readme

2022-01-20 13:14 UTC, aleksandr-mokrov approved these changes

2022-01-20 14:01 UTC, itrushkin approved these changes

2022-01-20 14:45 UTC, dmitryagapov approved these changes

2022-01-20 15:40 UTC, merged