Flake8-annotations: fix errors in databases
intel/openfl pull request #380
Opened 2022-03-15 09:53 UTC by ViktoriiaRomanova

Preparations to add [Flake8-annotations](https://pypi.org/project/flake8-annotations/)  plugin.

This fix is only for errors in **databases** folder.

It is assumed that the next flake8-annotations errors will be ignored:

ANN002 - Missing type annotation for `*args`
ANN003 - Missing type annotation for `**kwargs`
ANN101 - Missing type annotation for `self` in method
ANN102 - Missing type annotation for `cls` in classmethod

2022-03-16 08:43 UTC, ViktoriiaRomanova commented
Lenkins please retry a build

2022-03-16 08:47 UTC, ViktoriiaRomanova commented
Jenkins please retry a build

2022-03-16 09:14 UTC, dmitryagapov requested changes

2022-03-16 09:14 UTC, dmitryagapov commented on openfl/databases/tensor_db.py
> +    def cache_tensor(self, tensor_key_dict: dict) -> None:
Dict[TensorKey, np.ndarray]

2022-03-16 09:14 UTC, dmitryagapov commented on openfl/databases/tensor_db.py
> +    def get_aggregated_tensor(self, tensor_key: TensorKey, collaborator_weight_dict: dict,
`Any` -> `Type[AggregationFunction]`

2022-03-16 09:14 UTC, dmitryagapov commented on openfl/databases/tensor_db.py
> +    def _iterate(self, order_by: str = 'round', ascending: bool = False) -> Iterable:
Iterator[pd.Series]

2022-03-16 11:51 UTC, ViktoriiaRomanova commented
Jenkins please retry a build

2022-03-16 13:21 UTC, igor-davidyuk commented on openfl/databases/tensor_db.py
> +    def cache_tensor(self, tensor_key_dict: dict) -> None:
We have a strange function here called `cache_tensor` but accepting a dict with tensors 😁

2022-03-17 07:18 UTC, dmitryagapov approved these changes

2022-03-17 07:35 UTC, alexey-khorkin commented on openfl/databases/tensor_db.py
> +    def get_aggregated_tensor(self, tensor_key: TensorKey, collaborator_weight_dict: dict,
Why not just 
```python3
aggregation_function: AggregationFunction
``` 
?

2022-03-17 08:00 UTC, dmitryagapov commented on openfl/databases/tensor_db.py
> +    def get_aggregated_tensor(self, tensor_key: TensorKey, collaborator_weight_dict: dict,
Could be changed to `AggregationFunction`

2022-03-17 10:26 UTC, alexey-khorkin approved these changes

2022-03-17 19:21 UTC, igor-davidyuk approved these changes

2022-03-18 14:01 UTC, alexey-gruzdev approved these changes

2022-03-18 14:02 UTC, merged