Flake8-annotations: fix errors in openfl-tutorials
intel/openfl pull request #383
Opened 2022-03-16 10:35 UTC by ViktoriiaRomanova

Preparations to add [Flake8-annotations](https://pypi.org/project/flake8-annotations/) plugin (**optional changes**).

This fix is only for errors in **openfl-tutorials** folder.

It is assumed that the next flake8-annotations errors will be ignored:

ANN002 - Missing type annotation for `*args`
ANN003 - Missing type annotation for `**kwargs`
ANN101 - Missing type annotation for `self` in method
ANN102 - Missing type annotation for `cls` in classmethod

2022-03-16 11:15 UTC, ViktoriiaRomanova commented
Jenkins please retry a build

2022-03-17 13:06 UTC, ViktoriiaRomanova commented
Jenkins please retry a build

2022-04-05 14:49 UTC, itrushkin requested changes

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/MXNet_landmarks/workspace/mxnet_adapter.py
> +    def get_tensor_dict(model: Any,
Does MXNet contain base class for all models and blocks? We use `.collect_params()` method, is there any interface for it?

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_DogsCats_ViT/envoy/dogs_cats_shard_descriptor.py
> +    def calc_all_md5(self) -> Dict[str]:
What is the value type of the returned dictionary?

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor_with_data_splitter.py
> +                 enforce_image_hw: Optional[str] = None) -> None:
`enforce_image_hw` is an optional tuple. You did it right in the original (without data splitter) file.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor_with_data_splitter.py
> +    def __getitem__(self, index: int) -> tuple:
Please use `typing.Tuple`. Also, specify the types it should contain.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/kvasir_shard_descriptor_with_data_splitter.py
> +                 enforce_image_hw: Optional[str] = None) -> None:
`enforce_image_hw` is an optional tuple. You did it right in the original (without data splitter) file.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/workspace/layers.py
> +def soft_dice_loss(output: torch.tensor, target: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/workspace/layers.py
> +def soft_dice_coef(output: torch.tensor, target: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/workspace/layers.py
> +    def forward(self, x: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/workspace/layers.py
> +    def forward(self, x: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/workspace/layers.py
> +    def forward(self, x1: torch.tensor, x2: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Lightning_MNIST_GAN/envoy/mnist_shard_descriptor.py
> +    def __init__(self, x: Any, y: Any, data_type: str,
We pass NumPy arrays here.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Lightning_MNIST_GAN/workspace/plugin_for_multiple_optimizers.py
> +    def get_tensor_dict(model: Any, optimizers: Any = None) -> Dict[str, ndarray]:
`model` is a PyTorch module.

`optimizers` is a list of dictionaries or optimizers.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/envoy/mvtec_shard_descriptor.py
> +    def resize(self, image: np.ndarray, shape: Tuple[int, int] = (256, 256)) -> np.ndarray:
`shape` can be an arbitrary integer tuple.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/envoy/mvtec_shard_descriptor.py
> +    def sample_shape(self) -> List[str, str, str]:
For a list of strings, there is no need to specify the type of each element.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/envoy/mvtec_shard_descriptor.py
> +    def target_shape(self) -> List[str, str]:
For a list of strings, there is no need to specify the type of each element.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/data_transf.py
> +def bilinears(images: np.ndarray, shape: Tuple[int, int]) -> np.ndarray:
`shape` can be an arbitrary integer tuple.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/data_transf.py
> +def bal_acc_score(obj: Any, predictions: np.ndarray, labels: np.ndarray) -> float:
`obj` can be safely removed.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/data_transf.py
> +def detection_auroc(obj: Any, anomaly_scores: np.ndarray, labels: np.ndarray) -> float:
`obj` can be safely removed.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/data_transf.py
> +def segmentation_auroc(obj: Any, anomaly_maps: np.ndarray, masks: np.ndarray) -> float:
`obj` can be safely removed.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/inspection.py
> +def eval_embeddings_nn_maps(obj: Any, embs64: Tuple[np.ndarray, np.ndarray],
Can we remove unused parameters here?

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/utils.py
> +def crop_chw(image: Any, i: int, j: int, k: int, s: int = 1) -> Any:
Only NumPy-like arrays support multiple axis indexing.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/utils.py
> +def crop_image_chw(image: Any, coord: int, k: int) -> Any:
Only NumPy-like arrays support multiple axis indexing.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/utils.py
> +def load_binary(fpath: Any, encoding: str = 'ASCII') -> Any:
`fpath` could be `str` or `pathlib.Path`.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/utils.py
> +def save_binary(d: Any, fpath: Any) -> None:
`fpath` could be `str` or `pathlib.Path`.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/utils.py
> +def distribute_scores(score_masks: Any, output_shape: Any, k: int, s: int) -> np.ndarray:
`score_masks` should have `shape` attribute.

`output_shape` should be an arbitrary tuple of integers.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_MVTec_PatchSVDD/workspace/utils.py
> +def distribute_score(score_mask: Any, output_shape: Any, k: int, s: int) -> np.ndarray:
`score_masks` should have `shape` attribute.

`output_shape` should be an arbitrary tuple of integers.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/envoy/market_shard_descriptor.py
> +    def __getitem__(self, index: int) -> Tuple['Image', Tuple[int, int]]:
Why do we use quotes on `Image` type?

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/envoy/market_shard_descriptor.py
> +    def sample_shape(self) -> List[str, str, str]:
For a list of strings, there is no need to specify the type of each element.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/losses.py
> +    def forward(self, pred: torch.tensor, target: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/losses.py
> +    def forward(self, inputs: torch.tensor, targets: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +def extract_feature(model: Any,
`model` is a PyTorch module.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +                    dataloader: Any) -> Tuple[torch.tensor, torch.tensor, torch.tensor]:
`dataloader` can be iterable yielding tuples, but we pass here only PyTorch DataLoaders.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +def compute_ap_cmc(index: int, good_index: Any, junk_index: Any) -> Tuple[float, np.ndarray]:
for `*_index` arguments we pass only NumPy arrays.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +    def update(self, val: Any, n: Any = 1) -> None:
According to usage, `val` is expected to be a float number, and `n` is expected to be an integer number.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +             g_pids: torch.tensor, q_camids: torch.tensor,
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +                    dataloader: Any) -> Tuple[torch.tensor, torch.tensor, torch.tensor]:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +def fliplr(img: torch.tensor) -> torch.tensor:
Do not use functions as types.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/tools.py
> +    def __iter__(self) -> Iterable:
`__iter__` function always returns an `Iterator`.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/transforms.py
> +    def __init__(self, height: Union[float, int], width: Union[float, int],
Images can not be resized to a `float` dimensions.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/transforms.py
> +                 p: float = 0.5, interpolation: Any = Image.BILINEAR) -> None:
According to Pillow documentation for `Image.resize()`, `interpolation` is `Image.Resampling`
```python
           :param resample: An optional resampling filter.  This can be
           one of :py:data:`PIL.Image.Resampling.NEAREST`,
           :py:data:`PIL.Image.Resampling.BOX`,
           :py:data:`PIL.Image.Resampling.BILINEAR`,
           :py:data:`PIL.Image.Resampling.HAMMING`,
           :py:data:`PIL.Image.Resampling.BICUBIC` or
           :py:data:`PIL.Image.Resampling.LANCZOS`.
           If the image has mode "1" or "P", it is always set to
           :py:data:`PIL.Image.Resampling.NEAREST`.
           If the image mode specifies a number of bits, such as "I;16", then the
           default filter is :py:data:`PIL.Image.Resampling.NEAREST`.
           Otherwise, the default filter is
           :py:data:`PIL.Image.Resampling.BICUBIC`. See: :ref:`concept-filters`.
```

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_Market_Re-ID/workspace/transforms.py
> +                 mean: Optional[List[int]] = None) -> None:
Can mean have float values?

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_TinyImageNet/envoy/tinyimagenet_shard_descriptor.py
> +    def sample_shape(self) -> List[str, str, str]:
For a list of strings, there is no need to specify the type of each element.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/PyTorch_TinyImageNet/envoy/tinyimagenet_shard_descriptor.py
> +    def target_shape(self) -> List[str, str]:
For a list of strings, there is no need to specify the type of each element.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/Tensorflow_MNIST/workspace/layers.py
> +def create_model() -> Any:
This method always returns Keras Model.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/Tensorflow_Word_Prediction/envoy/shard_descriptor.py
> +                    train_val_split: float = 0.8) -> NextWordShardDataset:
This method might raise an exception in case of unsupported dataset type.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/Tensorflow_Word_Prediction/envoy/shard_descriptor.py
> +    def sample_shape(self) -> List[str, str]:
For a list of strings, there is no need to specify the type of each element.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/Tensorflow_Word_Prediction/envoy/shard_descriptor.py
> +    def load_data(path: Any) -> List[str]:
`path` should be a string or Path-like object.

2022-04-05 14:49 UTC, itrushkin commented on openfl-tutorials/interactive_api/numpy_linear_regression/workspace/custom_adapter.py
> +    def set_tensor_dict(model: Any, tensor_dict: Any,
`tensor_dict` is a specific dictionary.

2022-12-14 19:01 UTC, closed without merging