Straggler Handling Interface
intel/openfl pull request #441
Opened 2022-06-08 21:10 UTC by mansishr

This PR identifies stragglers for each task and excludes them from sending task results to aggregator. The two policies created are:

1. Cutoff Time based straggler handling: Straggler is not able to finish tasks for a round within a given cutoff time
2. Percentage based straggler handling: Based on %age, there are enough collaborators with task results to proceed for next round.

2022-06-15 22:31 UTC, psfoley commented on openfl/component/aggregator/aggregator.py
> +            # if named_tensor.round_number != round_number:
This block looks like it can be removed

2022-06-15 22:38 UTC, psfoley requested changes
Thanks Mansi for adding this interface.

A couple requests:

1. Could you add a new OpenFL workspace template that demonstrates how select a different straggler handling policy from the plan file? Also, I would expect to see changes within the plan.py file to initialize the referenced straggler policy. 
2. You should also add documentation about how to implement a new straggler handling policy.

2022-07-14 21:23 UTC, psfoley approved these changes

2022-07-14 21:23 UTC, merged

2022-08-01 14:44 UTC, igor-davidyuk commented on openfl/component/aggregator/aggregator.py
> +        straggler_check = self.straggler_handling_policy.straggler_cutoff_check(
is it a hardcoded method?

2022-08-01 18:55 UTC, igor-davidyuk commented on openfl-workspace/torch_cnn_mnist_straggler_check/plan/plan.yaml
> +straggler_handling_policy :
There should be a default template that would be copied if user ignored this section