Horovod demo
intel/openfl pull request #899
Opened 2023-11-29 20:44 UTC by porteratzo

2024-02-07 00:42 UTC, psfoley commented
@porteratzo could you add a description to this PR?

2024-02-22 23:29 UTC, psfoley requested changes
This is a great contribution, @porteratzo.  A couple small requested changes, and then I think this is ready to merge.

2024-02-22 23:29 UTC, psfoley commented on openfl-tutorials/experimental/Federeated_Pytorch_LLM_Horovod.py
> +# Run openfl-tutorials/experimental/setup_env.shsetup_env.sh in your venv to setup horovod dependancies
copy paste error

```suggestion
# Run openfl-tutorials/experimental/setup_env.sh in your venv to setup horovod dependancies
```

2024-02-22 23:29 UTC, psfoley commented on openfl-tutorials/experimental/LLM_Horovod.MD
This file should also be moved to `openfl-workspace/torch_llm_horovod`

2024-02-23 15:25 UTC, porteratzo commented on openfl-tutorials/experimental/Federeated_Pytorch_LLM_Horovod.py
> +# Run openfl-tutorials/experimental/setup_env.shsetup_env.sh in your venv to setup horovod dependancies
Fixed error and added description to PR

2024-02-23 15:26 UTC, porteratzo commented on openfl-tutorials/experimental/LLM_Horovod.MD
Moved file to openfl-workspace/torch_llm_horovod

2024-02-23 19:29 UTC, psfoley approved these changes

2024-02-23 19:30 UTC, merged